version: "3.8"

networks:
  reverse-proxy:
    external: true
  litellm:
    external: true

services:
  main:
    image: ghcr.io/open-webui/open-webui:0.10.2
    networks:
      - reverse-proxy
      - litellm
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.openwebui.rule=Host(`openwebui.actuary.dev`)"
        - "traefik.http.routers.openwebui.entrypoints=websecure"
        - "traefik.http.routers.openwebui.service=openwebui"
        - "traefik.http.routers.openwebui.tls.certresolver=myresolver"
        - "traefik.http.services.openwebui.loadbalancer.server.port=8080"
        - "traefik.http.routers.openwebui.middlewares=authentik@swarm"
    environment:
      - OPENAI_API_BASE_URL=http://litellm_main:4000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WEBUI_URL=https://openwebui.actuary.dev
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - WEBUI_AUTH_TRUSTED_EMAIL_HEADER=X-authentik-email
      - WEBUI_AUTH_TRUSTED_NAME_HEADER=X-authentik-name
      - ENABLE_LOGIN_FORM=false
      - JWT_EXPIRES_IN=72h
      - WEBUI_AUTH_COOKIE_SECURE=true
      # Web Search Configuration
      - ENABLE_WEB_SEARCH=True
      - WEB_SEARCH_ENGINE=searxng
      - WEB_SEARCH_RESULT_COUNT=3
      - WEB_SEARCH_CONCURRENT_REQUESTS=10
      - SEARXNG_QUERY_URL=http://searxng_main:8080/search?q=<query>
    volumes:
      - /mnt/user/docker/volumes/open-webui:/app/backend/data
