version: "3.9"

networks:
  reverse-proxy:
    external: true

services:
  [SERVICE]:
    image: [REPO]/[IMAGE]:[VERSION]
    networks:
      reverse-proxy:
    #command:
    #ports:
    #volumes:
    #  - /mnt/user/docker/volumes/[SERVICE]:/[FILEPATH]
    #environment:
    deploy:
      labels:
        # Traefik
        - "traefik.enable=true"
        - "traefik.http.routers.[SERVICE].rule=Host(`[SERVICE].actuary.dev`)"
        - "traefik.http.routers.[SERVICE].entrypoints=websecure"
        - "traefik.http.routers.[SERVICE].service=[SERVICE]"
        - "traefik.http.routers.[SERVICE].tls.certresolver=myresolver"
        - "traefik.http.services.[SERVICE].loadbalancer.server.port=6806"
        ## Middlewares
        - "traefik.http.routers.[SERVICE].middlewares=authentik"
        #DIUN
        - diun.enable = true
        - diun.notify_on = new
